### ISSUE TITLE
Active Development

### ISSUE THREAD

**Issue by sirinath** [spring-projects/spring-integration-dsl-scala#19]
Is this still in active development? If so what is the road map?

**Comment by orubel** [comment]
Scala development by Spring was dropped. You should try Groovy 3.0 which runs on Springboot and integrates 100% with Spring and Spring projects and is just as scalable and functional. :)

**Comment by garyrussell** [comment]
The Scala DSL is not currently actively developed; based on community feedback, we redirected our efforts towards the [Java DSL](https://github.com/spring-projects/spring-integration-java-dsl).
